var space = [
    {
        num: '1',
        title: 'GARDEN OF FLOWERS',
        date: 'January 16, 2024',
        time: '8:08:34 PM',
        location: 'Dali, China',
		image: '1.png',
        url: 'objects/1.html',
    },
    {
        num: '2',
        title: 'THE BASEMENT',
        date: 'January 16, 2024',
        time: '3:48:49 PM',
        location: 'Dali, China',
		image: '2.png',
        url: 'objects/2.html',
    },
    {
        num: '3',
        title: 'PAWS STRIPS',
        date: 'January 17, 2024',
        time: '2:44:50 PM',
        location: 'Dali, China',
		image: '3.png',
        url: 'objects/3.html',
    },
    {
        num: '4',
        title: 'OLD DREAMS',
        date: 'January 17, 2024',
        time: '2:49:43 PM',
        location: 'Dali, China',
		image: '4.png',
        url: 'objects/4.html',
    },
    {
        num: '5',
        title: 'LAKE OF SKY',
        date: 'January 17, 2024',
        time: '3:10:16 PM',
        location: 'Dali, China',
		image: '7.png',
        url: 'objects/5.html',
    },
    {
        num: '6',
        title: 'BURNED TRUNK',
        date: 'January 17, 2024',
        time: '10:57:35 PM',
        location: 'Dali, China',
		image: '8.png',
        url: 'objects/6.html',
    },
    {
        num: '7',
        title: 'UNKNOWN STONEART',
        date: 'February 29, 2024',
        time: '3:34:12 PM',
        location: 'NewYork, U.S.',
		image: '6.png',
        url: 'objects/7.html',
    },
    {
        num: '8',
        title: 'PIANO',
        date: 'March 1, 2024',
        time: '12:21:39 PM',
        location: 'NewYork, U.S.',
		image: '5.png',
        url: 'objects/8.html',
    },
    {
        num: '9',
        title: 'PIECE OF CLOTH',
        date: 'March 1, 2024',
        time: '12:30:44 PM',
        location: 'NewYork, U.S.',
		image: '9.png',
        url: 'objects/9.html',
    },
    {
        num: '10',
        title: 'Her Wardrobe',
        date: 'March 9, 2024',
        time: '3:52:44 PM',
        location: 'NewYork, U.S.',
		image: '16.png',
        url: 'objects/10.html',
    },
    {
        num: '11',
        title: 'Pancake',
        date: 'March 10, 2024',
        time: '1:56:39 PM',
        location: 'NewYork, U.S.',
		image: '17.png',
        url: 'objects/11.html',
    },
    {
        num: '12',
        title: 'Tie Dye',
        date: 'March 10, 2024',
        time: '2:00:51 PM',
        location: 'NewYork, U.S.',
		image: '18.png',
        url: 'objects/12.html',
    },
    {
        num: '13',
        title: 'Cliff',
        date: 'March 10, 2024',
        time: '2:12:29 PM',
        location: 'NewYork, U.S.',
		image: '19.png',
        url: 'objects/13.html',
    },
    {
        num: '14',
        title: 'Ribber Cut',
        date: 'March 10, 2024',
        time: '2:28:51 PM',
        location: 'NewYork, U.S.',
		image: '20.png',
        url: 'objects/14.html',
    },
    {
        num: '15',
        title: 'Gloomy Sea',
        date: 'March 10, 2024',
        time: '2:33:07 PM',
        location: 'NewYork, U.S.',
		image: '21.png',
        url: 'objects/15.html',
    },
    {
        num: '16',
        title: 'London Street',
        date: 'March 10, 2024',
        time: '2:38:12 PM',
        location: 'NewYork, U.S.',
		image: '22.png',
        url: 'objects/16.html',
    },
    {
        num: '17',
        title: 'Nihon',
        date: 'March 10, 2024',
        time: '2:49:14 PM',
        location: 'NewYork, U.S.',
		image: '23.png',
        url: 'objects/17.html',
    },{
        num: '18',
        title: 'FIRE IN HOUSE',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '10.png',
        url: 'objects/18.html',
    },
    {
        num: '19',
        title: 'ANCIENT LANDSCAPE',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '11.png',
        url: 'objects/19.html',
    },
    {
        num: '20',
        title: 'THE FACTORY',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '12.png',
        url: 'objects/20.html',
    },
    {
        num: '21',
        title: 'SUMMER MARKET',
        date: 'March 11, 2024',
        time: '5:01:29 PM',
        location: 'NewYork, U.S.',
		image: '13.png',
        url: 'objects/21.html',
    },
    {
        num: '22',
        title: 'DAMIEs ROOM',
        date: 'March 11, 2024',
        time: '5:03:01 PM',
        location: 'NewYork, U.S.',
		image: '14.png',
        url: 'objects/22.html',
    },
    {
        num: '23',
        title: 'ABANDONED HOUSE',
        date: 'March 11, 2024',
        time: '7:04:33 PM',
        location: 'NewYork, U.S.',
		image: '15.png',
        url: 'objects/23.html',
    },
    {
        num: '24',
        title: 'Candy Wrap',
        date: 'March 22, 2024',
        time: '12:12:20 PM',
        location: 'NewYork, U.S.',
		image: '24.png',
        url: 'objects/24.html',
    },
    {
        num: '25',
        title: 'Locker',
        date: 'March 24, 2024',
        time: '12:56:07 PM',
        location: 'NewYork, U.S.',
		image: '26.png',
        url: 'objects/25.html',
    },
    {
        num: '26',
        title: 'Tile',
        date: 'March 24, 2024',
        time: '4:21:41 PM',
        location: 'NewYork, U.S.',
		image: '25.png',
        url: 'objects/26.html',
    },
]