var space = [
    {
        num: '1',
        title: 'GARDEN OF FLOWERS',
        date: 'January 16, 2024',
        time: '8:08:34 PM',
        location: 'Dali, China',
		image: '1.png',
        url: 'objects/1/index.html',
    },
    {
        num: '2',
        title: 'THE BASEMENT',
        date: 'January 16, 2024',
        time: '3:48:49 PM',
        location: 'Dali, China',
		image: '2.png',
        url: 'objects/2/index.html',
    },
    {
        num: '3',
        title: 'PAWS STRIPS',
        date: 'January 17, 2024',
        time: '2:44:50 PM',
        location: 'Dali, China',
		image: '3.png',
        url: 'objects/3/index.html',
    },
    {
        num: '4',
        title: 'OLD DREAMS',
        date: 'January 17, 2024',
        time: '2:49:43 PM',
        location: 'Dali, China',
		image: '4.png',
        url: 'objects/4/index.html',
    },
    {
        num: '5',
        title: 'LAKE OF SKY',
        date: 'January 17, 2024',
        time: '3:10:16 PM',
        location: 'Dali, China',
		image: '7.png',
        url: 'objects/5/index.html',
    },
    {
        num: '6',
        title: 'BURNED TRUNK',
        date: 'January 17, 2024',
        time: '10:57:35 PM',
        location: 'Dali, China',
		image: '8.png',
        url: 'objects/6/index.html',
    },
    {
        num: '7',
        title: 'UNKNOWN STONEART',
        date: 'February 29, 2024',
        time: '3:34:12 PM',
        location: 'NewYork, U.S.',
		image: '6.png',
        url: 'objects/7/index.html',
    },
    {
        num: '8',
        title: 'PIANO',
        date: 'March 1, 2024',
        time: '12:21:39 PM',
        location: 'NewYork, U.S.',
		image: '5.png',
        url: 'objects/8/index.html',
    },
    {
        num: '9',
        title: 'PIECE OF CLOTH',
        date: 'March 1, 2024',
        time: '12:30:44 PM',
        location: 'NewYork, U.S.',
		image: '9.png',
        url: 'objects/9/index.html',
    },
    {
        num: '10',
        title: 'HER WARDROBE',
        date: 'March 9, 2024',
        time: '3:52:44 PM',
        location: 'NewYork, U.S.',
		image: '16.png',
        url: 'objects/10/index.html',
    },
    {
        num: '11',
        title: 'PANCAKE',
        date: 'March 10, 2024',
        time: '1:56:39 PM',
        location: 'NewYork, U.S.',
		image: '17.png',
        url: 'objects/11/index.html',
    },
    {
        num: '12',
        title: 'TIE DYE',
        date: 'March 10, 2024',
        time: '2:00:51 PM',
        location: 'NewYork, U.S.',
		image: '18.png',
        url: 'objects/12/index.html',
    },
    {
        num: '13',
        title: 'CLIFF',
        date: 'March 10, 2024',
        time: '2:12:29 PM',
        location: 'NewYork, U.S.',
		image: '19.png',
        url: 'objects/13/index.html',
    },
    {
        num: '14',
        title: 'RUBBER CUT',
        date: 'March 10, 2024',
        time: '2:28:51 PM',
        location: 'NewYork, U.S.',
		image: '20.png',
        url: 'objects/14/index.html',
    },
    {
        num: '15',
        title: 'GLOOMY SEA',
        date: 'March 10, 2024',
        time: '2:33:07 PM',
        location: 'NewYork, U.S.',
		image: '21.png',
        url: 'objects/15/index.html',
    },
    {
        num: '16',
        title: 'LONDON STREET',
        date: 'March 10, 2024',
        time: '2:38:12 PM',
        location: 'NewYork, U.S.',
		image: '22.png',
        url: 'objects/16/index.html',
    },
    {
        num: '17',
        title: 'NIHON',
        date: 'March 10, 2024',
        time: '2:49:14 PM',
        location: 'NewYork, U.S.',
		image: '23.png',
        url: 'objects/17/index.html',
    },{
        num: '18',
        title: 'FIRE IN HOUSE',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '10.png',
        url: 'objects/18/index.html',
    },
    {
        num: '19',
        title: 'ANCIENT LANDSCAPE',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '11.png',
        url: 'objects/19/index.html',
    },
    {
        num: '20',
        title: 'THE FACTORY',
        date: 'March 11, 2024',
        time: '12:30:07 PM',
        location: 'NewYork, U.S.',
		image: '12.png',
        url: 'objects/20/index.html',
    },
    {
        num: '21',
        title: 'SUMMER MARKET',
        date: 'March 11, 2024',
        time: '5:01:29 PM',
        location: 'NewYork, U.S.',
		image: '13.png',
        url: 'objects/21/index.html',
    },
    {
        num: '22',
        title: 'DAMIES ROOM',
        date: 'March 11, 2024',
        time: '5:03:01 PM',
        location: 'NewYork, U.S.',
		image: '14.png',
        url: 'objects/22/index.html',
    },
    {
        num: '23',
        title: 'ABANDONED HOUSE',
        date: 'March 11, 2024',
        time: '7:04:33 PM',
        location: 'NewYork, U.S.',
		image: '15.png',
        url: 'objects/23/index.html',
    },
    {
        num: '24',
        title: 'CANDY WRAP',
        date: 'March 22, 2024',
        time: '12:12:20 PM',
        location: 'NewYork, U.S.',
		image: '24.png',
        url: 'objects/24/index.html',
    },
    {
        num: '25',
        title: 'LOCKER',
        date: 'March 24, 2024',
        time: '12:56:07 PM',
        location: 'NewYork, U.S.',
		image: '26.png',
        url: 'objects/25/index.html',
    },
    {
        num: '26',
        title: 'TILE',
        date: 'March 24, 2024',
        time: '4:21:41 PM',
        location: 'NewYork, U.S.',
		image: '25.png',
        url: 'objects/26/index.html',
    },
]